import type { LearningActivity, StepDetail, SubmitResponse } from '../../types/learning';

/** Props every activity runner (lesson / quiz / flashcards / discussion / recall) accepts. */
export interface ActivityRunnerProps {
  /** The in-progress activity (content already generated by the server). */
  activity: LearningActivity;
  /** The step it belongs to (title, objectives, skill, ids for navigation). */
  step: StepDetail;
  /** Called with the server's grading/outcome once the activity is submitted. */
  onComplete: (result: SubmitResponse) => void;
  /** The learner backed out without finishing (the page abandons the activity). */
  onAbandon: () => void;
}
